### ISSUE TITLE
Mysterious disappearing underscores

### ISSUE THREAD

**Issue by theosanderson** [theosanderson/taxodium#18]
![Screenshot_20210706-024727](https://user-images.githubusercontent.com/19732295/124530570-a9817080-de04-11eb-9521-c5c3c8c1914f.png)

**Comment by theosanderson** [comment]
Looks like another data norming issue actually

**Comment by AngieHinrichs** [comment]
Yes, sorry about that... short version: spaces in GISAID sequence names are stripped by Nextstrain but replaced with underscores by COG-UK.  Initially I was using the Nextstrain-generated fasta and metadata available from gisaid.org, but I lost access to those files in December.  By that point I was accustomed to stripping out spaces and continued to do that with INSDC sequences.  But when I integrated the COG-UK files, it seemed wrong to strip out the underscores.  So now we have this unfortunate mix where if there is an INSDC accession, it's NorthernIreland and if there's not (i.e. direct from COG-UK) it's Northern_Ireland.

**Comment by theosanderson** [comment]
No problem @AngieHinrichs ! (And thanks for the explanation). I also do some playing with underscores so when I spotted this I thought it might be at my end so made the issue to remember in case it was that. I might change this in post for these seqs but will think about how that effects those using the UShER tree.
