### ISSUE TITLE
Download current view as image

### ISSUE THREAD

**Issue by yatisht** [theosanderson/taxodium#69]
Hey Theo,

This is  a low-priority enhancement request – would it be easy for you to add a feature to download the current view on Taxodium as an image file (e.g. png)? Taking snapshots can sometimes be time-consuming sometimes and inconsistent. Thanks.

-Yatish

**Comment by theosanderson** [comment]
Turned out to be pretty easy :) 
![image](https://user-images.githubusercontent.com/19732295/135758425-282d3525-c139-4268-b880-5981dbf31c14.png)

**Comment by theosanderson** [comment]
Hmm on one occasion I got an empty screenshot so this may not be foolproof - interested to hear if you have similar issues

**Comment by yatisht** [comment]
It has worked great for me so far. Thanks so much for such a quick response!
