### ISSUE TITLE
Bug: search is case-sensitive

### ISSUE THREAD

**Issue by Mike-Honey** [theosanderson/taxodium#8]
I've tried a few searches (country=australia, lineage=b.1.617.2), but they don't have any impact on the tree displayed?

Do I just type text into the search box? There's no search button?

Perhaps a count of the search hits might also help?

 I'm using Chrome 91.

**Comment by theosanderson** [comment]
Apologies, it's case sensitive atm :( I'll fix that

**Comment by theosanderson** [comment]
Thanks for the report. Mutations are still case sensitive I'm afraid. I'll put that on the backlog.
